// Test generated by RoostGPT for test nodetest-nov using AI Type Azure Open AI and AI Model roost-gpt4-32k

const request = require('supertest');
const express = require('express');
const app = require('./app');

describe('Error Middleware', () => {
    it('should handle error correctly in development mode', async () => {
        app.get('/error', (req, res, next) => {
            next(createError(500, "Test error"));
        });

        process.env.NODE_ENV = 'development';

        const response = await request(app).get('/error');

        expect(response.statusCode).toBe(500);
        expect(response.text).toMatch(/Test error/);
        expect(response.text).toMatch(/Error: Test error/);

        delete process.env.NODE_ENV;
    });

    it('should handle error correctly not in development mode', async () => {
        app.get('/error', (req, res, next) => {
            next(createError(500, "Test error"));
        });

        const response = await request(app).get('/error');

        expect(response.statusCode).toBe(500);
        expect(response.text).toMatch(/Test error/);
        expect(response.text).not.toMatch(/Error: Test error/);
    });
});
