// Test generated by RoostGPT for test nodetest-nov using AI Type Azure Open AI and AI Model roost-gpt4-32k

const CryptoJS = require("crypto-js");
const { hashPassword } = require("./create-user-cli");

describe("hashPassword", () => {
  beforeEach(() => {
    jest.resetModules()
  });

  test("It should return hashed password", () => {
    const password = "test123";
    const hashedPassword = hashPassword(password);
    const expectedHashedPassword = CryptoJS.SHA256(password).toString();
    
    expect(hashedPassword).toBe(expectedHashedPassword);
  });

  test("It should return different hash for different passwords", () => {
    const password1 = "test123";
    const password2 = "test321";
    const hashedPassword1 = hashPassword(password1);
    const hashedPassword2 = hashPassword(password2);
    
    expect(hashedPassword1).not.toBe(hashedPassword2);
  });

  test("It should throw an error if password is not a string", () => {
    const password = 123456;
  
    expect(() => hashPassword(password)).toThrow(TypeError);
  });
});
