// Test generated by RoostGPT for test nodetest-nov using AI Type Azure Open AI and AI Model roost-gpt4-32k

const request = require('supertest');
const express = require('express');
const createError = require('http-errors');
 
let app;
app = express();

app.use(function(req, res, next) {
  next(createError(404));
})

describe('404 error handler', () => {
  test('it should return a 404 status code', async () => {
    const res = await request(app)
      .get('/someNonExistingEndpoint')
 
    expect(res.statusCode).toEqual(404);
  });

  test('it should return a html response', async () => {
    const res = await request(app)
      .get('/someNonExistingEndpoint')

    expect(res.headers['content-type']).toEqual(expect.stringContaining('html'));
  });
});
