// Test generated by RoostGPT for test nodetest-nov using AI Type Azure Open AI and AI Model roost-gpt4-32k

const request = require('supertest');
const express = require('express');
const app = express();
const router = require('./admin');

app.use(router);

describe('Testing /delete/:id endpoint', () => {

  beforeEach(() => {
    // Setup   
    id = '608d1c86e4920c0011cf5a85'; // A valid id from your Post collection
  });

  test('It should response with redirecting on success', async () => {
    const response = await request(app).get(`/delete/${id}`);
    expect(response.statusCode).toBe(302);
    expect(response.headers.location).toBe('/admin/');
  });

  test('It should response with 404 status code when post not found', async () => {
    const response = await request(app).get('/delete/incorrectId');
    expect(response.statusCode).toBe(404);
  });

  test('should handle database error', async () => {
    const response = await request(app).get('/delete/a'); //this will cause CastError
    expect(response.statusCode).toBe(500);
  });

  afterEach(() => {
    // Teardown
    id = null;
  });
});
