// Test generated by RoostGPT for test nodetest-nov using AI Type Azure Open AI and AI Model roost-gpt4-32k

const app = require('../app');
const request = require('supertest');
const Cookies = require('cookies');

jest.mock('cookies');


describe('Authentication Test Suite', () => {
    let server;

    beforeAll(() => {
        server = app.listen();
    });

    afterEach(() => {
        jest.clearAllMocks();
    });

    afterAll((done) => {
        server.close(done);
    });

    test('should redirect to login on no user in cookies', async () => {
        Cookies.mockImplementation(() => ({ get: () => undefined }));
        const response = await request(app).get('/path-to-be-authenticated');
        expect(response.statusCode).toBe(302);
        expect(response.headers.location).toBe('/admin/login');
    });

    test('should set req.user if user in cookies', async () => {
        Cookies.mockImplementation(() => ({ get: () => 'user' }));
        const response = await request(app).get('/path-to-be-authenticated');
        expect(response.request._headers.cookie).toBeDefined();
    });
});
